import type { Session } from '@/lib/opencode/model';

// Recap + suggested follow-up generated by the server's session-assist
// watcher, stored under session.metadata.openchamber.assist. forMessageID
// names the answer it was written for; freshness is decided by
// getCurrentSessionAssist from session fields alone.
export interface SessionAssistPayload {
  recap: string;
  suggestion: string;
  forMessageID: string;
  generatedAt: number;
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value) && typeof value === 'object' && !Array.isArray(value);

export function getSessionAssist(session: Session | null | undefined): SessionAssistPayload | null {
  const metadata = (session as { metadata?: unknown } | null | undefined)?.metadata;
  if (!isRecord(metadata)) return null;
  const namespace = metadata.openchamber;
  if (!isRecord(namespace)) return null;
  const assist = namespace.assist;
  if (!isRecord(assist)) return null;

  const recap = typeof assist.recap === 'string' ? assist.recap.trim() : '';
  const suggestion = typeof assist.suggestion === 'string' ? assist.suggestion.trim() : '';
  const forMessageID = typeof assist.forMessageID === 'string' ? assist.forMessageID : '';
  if (!forMessageID || (!recap && !suggestion)) return null;

  return {
    recap,
    suggestion,
    forMessageID,
    generatedAt: typeof assist.generatedAt === 'number' ? assist.generatedAt : 0,
  };
}

/**
 * The one freshness rule for a stored assist, shared by the sidebar row's
 * recap tooltip (which has only the session record) and the chat (which must
 * agree with it).
 * OpenCode stamps `time.idle` whenever a turn ends, succeeded or not, and the
 * assist is generated after that quiet turn end. A later turn moves `idle`
 * past `generatedAt`, so the payload describes an older turn and is retired.
 * A reverted session shows history that is no longer the active conversation.
 * The server also deletes the assist when a new turn starts; this rule covers
 * payloads written before that, or by another process.
 * Callers still hide it while a turn runs.
 */
export function getCurrentSessionAssist(session: Session | null | undefined): SessionAssistPayload | null {
  const assist = getSessionAssist(session);
  if (!assist || !session) return null;
  if (session.revert?.messageID) return null;
  const idleAt = session.time?.idle ?? 0;
  return assist.generatedAt >= idleAt ? assist : null;
}
