// Adapted from T3 Code's libghostty-vt browser adapter (MIT, T3 Tools Inc.).
// See LICENSE-T3CODE in this directory.

type WasmFunction = (...args: Array<number | bigint>) => number;

interface TypeField {
  readonly offset: number;
  readonly size: number;
  readonly type: string;
}

interface TypeLayout {
  readonly size: number;
  readonly align: number;
  readonly fields: Readonly<Record<string, TypeField>>;
}

type TypeLayouts = Readonly<Record<string, TypeLayout>>;

const textDecoder = new TextDecoder();

// The vendored artifact is fetched at runtime; `new URL` keeps this a plain
// static asset for Vite in every surface (web, VS Code webview, Electron's
// openchamber-ui:// protocol) and a readable file URL under bun's test runner.
const ghosttyWasmUrl = new URL('./vendor/ghostty-vt.wasm', import.meta.url);

/**
 * Compiled from scripts/ghostty-write-pty.zig: one exported function that
 * forwards libghostty-vt's write-PTY callback to the `openchamber_write_pty`
 * import. Embedding the 121 bytes avoids a second network fetch and any CSP
 * question about data: URLs.
 */
const WRITE_PTY_TRAMPOLINE = Uint8Array.from([
  0, 97, 115, 109, 1, 0, 0, 0, 1, 8, 1, 96, 4, 127, 127, 127, 127, 0, 2, 29, 1, 3, 101, 110, 118,
  21, 111, 112, 101, 110, 99, 104, 97, 109, 98, 101, 114, 95, 119, 114, 105, 116, 101, 95, 112,
  116, 121, 0, 0, 3, 2, 1, 0, 5, 3, 1, 0, 16, 6, 9, 1, 127, 1, 65, 128, 128, 192, 0, 11, 7, 30, 2,
  6, 109, 101, 109, 111, 114, 121, 2, 0, 17, 103, 104, 111, 115, 116, 116, 121, 95, 119, 114,
  105, 116, 101, 95, 112, 116, 121, 0, 1, 10, 18, 1, 16, 0, 32, 0, 32, 1, 32, 2, 32, 3, 16, 128,
  128, 128, 128, 0, 11,
]);

export class GhosttyRuntime {
  readonly memory: WebAssembly.Memory;
  readonly layouts: TypeLayouts;
  private readonly exports: WebAssembly.Exports;
  private memoryView: DataView;
  private readonly ptyWriters = new Map<number, (data: string) => void>();
  private nextPtyWriterId = 1;
  private writePtyFunctionIndex = 0;

  private constructor(instance: WebAssembly.Instance) {
    this.exports = instance.exports;
    const memory = instance.exports.memory;
    if (!(memory instanceof WebAssembly.Memory)) {
      throw new Error('libghostty-vt did not export WebAssembly memory');
    }
    this.memory = memory;
    this.memoryView = new DataView(memory.buffer);
    const jsonPointer = this.call('ghostty_type_json');
    const bytes = new Uint8Array(memory.buffer);
    let end = jsonPointer;
    while (end < bytes.length && bytes[end] !== 0) end += 1;
    // SAFETY: ghostty_type_json is generated by the pinned libghostty-vt build
    // from its own C ABI structs; runtime.test.ts verifies the artifact matches
    // VERSION, so the document has exactly this shape.
    this.layouts = JSON.parse(textDecoder.decode(bytes.subarray(jsonPointer, end))) as TypeLayouts;
  }

  static async load(bytes?: ArrayBuffer): Promise<GhosttyRuntime> {
    const wasmBytes = bytes ?? (await fetchGhosttyWasm());
    // The log import needs the instance's memory, which only exists once
    // instantiation returns; the holder closes that loop.
    const instanceHolder: { current: WebAssembly.Instance | null } = { current: null };
    const imports = {
      env: {
        log: (pointer: number, length: number) => {
          const memory = instanceHolder.current?.exports.memory;
          if (!(memory instanceof WebAssembly.Memory)) return;
          const message = textDecoder.decode(new Uint8Array(memory.buffer, pointer, length));
          console.debug('[libghostty-vt]', message);
        },
      },
    };
    const result = await WebAssembly.instantiate(wasmBytes, imports);
    instanceHolder.current = result.instance;
    const runtime = new GhosttyRuntime(result.instance);
    await runtime.installWritePtyTrampoline();
    return runtime;
  }

  call(name: string, ...args: Array<number | bigint>): number {
    const fn = this.exports[name];
    if (!(fn instanceof Function)) {
      throw new Error(`libghostty-vt export is unavailable: ${name}`);
    }
    // SAFETY: every libghostty-vt export takes and returns wasm32 scalars (i32/i64).
    return (fn as WasmFunction)(...args);
  }

  layout(name: string): TypeLayout {
    const layout = this.layouts[name];
    if (!layout) throw new Error(`libghostty-vt type layout is unavailable: ${name}`);
    return layout;
  }

  alloc(size: number): number {
    const pointer = this.call('ghostty_wasm_alloc_u8_array', size);
    if (pointer === 0) throw new Error(`libghostty-vt failed to allocate ${size} bytes`);
    new Uint8Array(this.memory.buffer, pointer, size).fill(0);
    return pointer;
  }

  free(pointer: number, size: number): void {
    if (pointer !== 0) this.call('ghostty_wasm_free_u8_array', pointer, size);
  }

  allocOpaque(): number {
    const pointer = this.call('ghostty_wasm_alloc_opaque');
    if (pointer === 0) throw new Error('libghostty-vt failed to allocate an opaque pointer');
    // The slot is uninitialized until a *_new call writes it; zero it so dispose
    // paths that run after a partial initialization never free a garbage pointer.
    new DataView(this.memory.buffer).setUint32(pointer, 0, true);
    return pointer;
  }

  freeOpaque(pointer: number): void {
    if (pointer !== 0) this.call('ghostty_wasm_free_opaque', pointer);
  }

  readPointer(slot: number): number {
    return this.currentMemoryView().getUint32(slot, true);
  }

  attachPtyWriter(terminal: number, writer: (data: string) => void): number {
    if (this.writePtyFunctionIndex === 0) {
      throw new Error('libghostty-vt PTY callback trampoline is unavailable');
    }
    const id = this.nextPtyWriterId++;
    this.ptyWriters.set(id, writer);
    this.call('ghostty_terminal_set', terminal, 0, id);
    this.call('ghostty_terminal_set', terminal, 1, this.writePtyFunctionIndex);
    return id;
  }

  detachPtyWriter(terminal: number, id: number): void {
    this.call('ghostty_terminal_set', terminal, 1, 0);
    this.call('ghostty_terminal_set', terminal, 0, 0);
    this.ptyWriters.delete(id);
  }

  view(pointer: number, size?: number): DataView {
    return new DataView(this.memory.buffer, pointer, size);
  }

  bytes(pointer: number, size: number): Uint8Array {
    return new Uint8Array(this.memory.buffer, pointer, size);
  }

  /** Reuse scalar reads across cells, refreshing after any terminal grows shared WASM memory. */
  private currentMemoryView(): DataView {
    if (this.memoryView.buffer !== this.memory.buffer) {
      this.memoryView = new DataView(this.memory.buffer);
    }
    return this.memoryView;
  }

  setField(pointer: number, structName: string, fieldName: string, value: number): void {
    const field = this.layout(structName).fields[fieldName];
    if (!field) throw new Error(`libghostty-vt field is unavailable: ${structName}.${fieldName}`);
    const view = this.currentMemoryView();
    const offset = pointer + field.offset;
    switch (field.type) {
      case 'bool':
      case 'u8':
        view.setUint8(offset, value);
        return;
      case 'u16':
        view.setUint16(offset, value, true);
        return;
      case 'i32':
        view.setInt32(offset, value, true);
        return;
      case 'u32':
      case 'enum':
        view.setUint32(offset, value, true);
        return;
      case 'u64':
        view.setBigUint64(offset, BigInt(value), true);
        return;
      default:
        throw new Error(`Unsupported libghostty-vt field type: ${field.type}`);
    }
  }

  readField(pointer: number, structName: string, fieldName: string): number {
    const field = this.layout(structName).fields[fieldName];
    if (!field) throw new Error(`libghostty-vt field is unavailable: ${structName}.${fieldName}`);
    const view = this.currentMemoryView();
    const offset = pointer + field.offset;
    switch (field.type) {
      case 'bool':
      case 'u8':
        return view.getUint8(offset);
      case 'u16':
        return view.getUint16(offset, true);
      case 'i32':
        return view.getInt32(offset, true);
      case 'u32':
      case 'enum':
        return view.getUint32(offset, true);
      case 'u64':
        return Number(view.getBigUint64(offset, true));
      default:
        throw new Error(`Unsupported libghostty-vt field type: ${field.type}`);
    }
  }

  private async installWritePtyTrampoline(): Promise<void> {
    const result = await WebAssembly.instantiate(WRITE_PTY_TRAMPOLINE, {
      env: {
        openchamber_write_pty: (_terminal: number, userdata: number, pointer: number, length: number) => {
          const writer = this.ptyWriters.get(userdata);
          if (!writer || length === 0) return;
          writer(textDecoder.decode(new Uint8Array(this.memory.buffer, pointer, length)));
        },
      },
    });
    const trampoline = result.instance.exports.ghostty_write_pty;
    const table = this.exports.__indirect_function_table;
    if (!(trampoline instanceof Function) || !(table instanceof WebAssembly.Table)) {
      throw new Error('libghostty-vt did not expose its callback table');
    }
    const index = table.length;
    // grow-then-set instead of grow(1, fn): WebKit stores a grow init value
    // with broken type information and every later call_indirect through the
    // entry traps with a signature mismatch. table.set canonicalizes correctly.
    table.grow(1);
    table.set(index, trampoline);
    this.writePtyFunctionIndex = index;
  }
}

async function fetchGhosttyWasm(): Promise<ArrayBuffer> {
  const response = await fetch(ghosttyWasmUrl);
  if (!response.ok) {
    throw new Error(`Unable to load libghostty-vt (${response.status})`);
  }
  return response.arrayBuffer();
}

let runtimePromise: Promise<GhosttyRuntime> | null = null;

/** One WebAssembly instance per page; every terminal owns and frees its own handles inside it. */
export function loadGhosttyRuntime(): Promise<GhosttyRuntime> {
  runtimePromise ??= GhosttyRuntime.load().catch((error) => {
    runtimePromise = null;
    throw error;
  });
  return runtimePromise;
}
